### ISSUE TITLE
bake-0.5 

### ISSUE THREAD

**Issue by DanBurton** [ndmitchell/bake#44]
As seen on the Stackage build server:

```
[13 of 27] Compiling General.Web      ( src/General/Web.hs, dist/build/General/Web.o )

src/General/Web.hs:76:21: error:
    Variable not in scope: conduitManagerSettings :: ManagerSettings
   |
76 |     m <- newManager conduitManagerSettings
   |                     ^^^^^^^^^^^^^^^^^^^^^^
```

I was able to reproduce this build failure locally like so:

```bash
stack unpack bake-0.5 && cd bake-0.5
edit stack.yaml # add the following stack.yaml
stack build
```

```yaml
# stack.yaml
resolver: nightly-2018-03-10
extra-deps:
- http-conduit-2.3.0
```
